# Generated by Django 4.2.2 on 2023-10-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_username_review_useremail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='photo',
            field=models.ImageField(upload_to='tour/images/'),
        ),
    ]
