# Generated by Django 4.2.2 on 2023-10-06 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_tour_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_phone',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='tour',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
    ]
