# Generated by Django 4.2.2 on 2023-10-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_booking_booking_date_alter_booking_guest_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.IntegerField(),
        ),
    ]
