# Generated by Django 4.2.2 on 2023-10-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_tour_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_size',
            field=models.IntegerField(),
        ),
    ]
